### ISSUE TITLE
Construir Modelo de Web Scraping

### ISSUE THREAD

**Issue by isaacpcaraujo** [Ramo-Estudantil-IEEE-UFBA/CovidPrediction#5]

**Comment by isaacpcaraujo** [comment]
Construir um Scraping/Crawler para aquisição de dados de COVID do site: https://bi.saude.ba.gov.br/transparencia/

**Comment by taffarel55** [comment]
Olá @isaacpcaraujo.

Os dados serão obtidos da página ou do arquivo de planilhas?

**Comment by isaacpcaraujo** [comment]
> Olá @isaacpcaraujo.
> 
> Os dados serão obtidos da página ou do arquivo de planilhas?

Da pagina mesmo. Creio eu
