### ISSUE TITLE
DeprecationWarning: use options instead of chrome_options   wd_chrome = webdriver.Chrome(chrome_options=chrome_options)

### ISSUE THREAD

**Issue by taffarel55** [Ramo-Estudantil-IEEE-UFBA/CovidPrediction#8]
Ao executar a seguinte linha no arquivo do WebScraping:

```wd_chrome = webdriver.Chrome(chrome_options=chrome_options)```
 
Eu tenho esse erro:

```
/tmp/ipykernel_5286/3443727308.py:1: DeprecationWarning: use options instead of chrome_options
  wd_chrome = webdriver.Chrome(chrome_options=chrome_options)
WebDriverException: Message: unknown error: DevToolsActivePort file doesn't exist
```

Acredito que seja prudente a gente atualizar isso!

**Comment by taffarel55** [comment]
Com a gente acabou indo por outro caminho no desenvolvimento, não utilizando selenium por exemplo fecharei acho que não faz sentido manter essa issue aberta. Se a gente tiver esse problema no futuro, volto a abrir.

**Comment by isaacpcaraujo** [comment]
Beleza, tudo certo. Vou começar a parte da Análise Exploratória!
